config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/teacher'

  get 'dashboard/student'

  get 'dashboard/parent'

  get 'sessions/login'

  get 'login' =>'sessions#login'

  post 'sessions/login'

  get 'sessions/logout'

  resources :parents
  resources :students
  resources :assignments
  resources :courses
  resources :teachers

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :check_teacher, only: [:teacher]
  before_action :check_student, only: [:student]
  before_action :check_parent, only: [:parent]

  def teacher
    @teacher = Teacher.find_by_id(session[:teacher_id])
    @students = Student.all
  end

  def student
    @student = Student.find_by_id(session[:student_id])
  end

  def parent
    @parent = Parent.find_by_id(session[:parent_id])
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/parent.html.erb
<h1>Welcome <%= @parent.name %></h1>
<div class = "modern">
<div id="container" class = "main-container">
  <% @parent.student.courses.each do |course| %>
    <% sum_grades = 0 %>
      <div class = "row">
        <div class = "col-md-12"><h1>Course: <%= course.name %></h1></div>
      </div>
      <div class = "row">
        <div class = "col-md-4"><h3>Name</h3></div>
        <div class = "col-md-1"><h3>Grade</h3></div>
        <div class = "col-md-1"><h3>Percent</h3></div>
        <div class = "col-md-2"><h3>Percent of Final Grade</h3></div>
      </div>
      <div class = "scroller" margin-right = "-100px">
      <% course.assignments.each do |assignment| %>
        <% if assignment.student_id == @parent.student.id %>
          <div class = "row">
            <div class = "col-md-4"><%= assignment.name %></div>
            <div class = "col-md-1"><%= assignment.grade %></div>
            <div class = "col-md-1"><%= assignment.percent_of_total %></div>
            <div class = "col-md-2"><%= assignment.percent_of_final %></div>
            <% sum_grades += assignment.percent_of_final %>
          </div>
        <% end %>
      <% end %>
      </div>
      <div class = "row">
        <div class = "col-md-4"><h3>Total</h3></div>
        <div class = "col-md-2"></div>
        <div class = "col-md-2"><h3><%= sum_grades %>/100</h3></div>
      </div>
  <% end %>
</div>
</div>

app/views/dashboard/student.html.erb
<h1>Welcome <%= @student.name %></h1>
<div class = "modern">
<div id="container" class = "main-container">
  <% @student.courses.each do |course| %>
    <% sum_grades = 0 %>
      <div class = "row">
        <div class = "col-md-12"><h1>Course: <%= course.name %></h1></div>
      </div>
      <div class = "row">
        <div class = "col-md-4"><h3>Name</h3></div>
        <div class = "col-md-1"><h3>Grade</h3></div>
        <div class = "col-md-1"><h3>Percent</h3></div>
        <div class = "col-md-2"><h3>Percent of Final Grade</h3></div>
      </div>
      <div class = "scroller" margin-right = "-100px">
      <% course.assignments.each do |assignment| %>
        <% if assignment.student_id == @student.id %>
          <div class = "row">
            <div class = "col-md-4"><%= assignment.name %></div>
            <div class = "col-md-1"><%= assignment.grade %></div>
            <div class = "col-md-1"><%= assignment.percent_of_total %></div>
            <div class = "col-md-2"><%= assignment.percent_of_final %></div>
            <% sum_grades += assignment.percent_of_final %>
          </div>
        <% end %>
      <% end %>
      </div>
      <div class = "row">
        <div class = "col-md-4"><h3>Total</h3></div>
        <div class = "col-md-2"></div>
        <div class = "col-md-2"><h3><%= sum_grades %>/100</h3></div>
      </div>
  <% end %>
</div>
</div>

app/views/dashboard/teacher.html.erb
<h1>Welcome <%= @teacher.name %></h1>
<div class = "modern">
  <div id="container" class = "main-container">
    <% @teacher.courses.each do |course| %>
      <% sum_grades = 0 %>
      <div class = "row">
        <div class = "col-md-12"><h1>Course: <%= course.name %></h1></div>
      </div>
      <% @students.where(id: course.student_id).each do |student| %>
      <div class = "row">
        <div class = "col-md-12"><h1>Student: <%= student.name %></h1></div>
      </div>
        <div class = "row">
          <div class = "col-md-4"><h3>Name</h3></div>
          <div class = "col-md-1"><h3>Grade</h3></div>
          <div class = "col-md-1"><h3>Percent</h3></div>
          <div class = "col-md-2"><h3>Percent of Final Grade</h3></div>
        </div>
        <div class = "scroller" margin-right = "-100px">
          <% course.assignments.each do |assignment| %>
            <% if assignment.student_id == student.id %>
              <div class = "row">
                <div class = "col-md-4"><%= assignment.name %></div>
                <div class = "col-md-1"><%= assignment.grade %></div>
                <div class = "col-md-1"><%= assignment.percent_of_total %></div>
                <div class = "col-md-2"><%= assignment.percent_of_final %></div>
                <% sum_grades += assignment.percent_of_final %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <div class = "row">
        <div class = "col-md-4"><h3>Total</h3></div>
        <div class = "col-md-2"></div>
        <div class = "col-md-2"><h3><%= sum_grades %>/100</h3></div>
      </div>
    <% end %>

  </div>
</div>
<%= link_to 'Assignmets', assignments_path %>
<%= link_to 'Students', students_path %>
<%= link_to 'Parents', parents_path %>
<%= link_to 'Courses', courses_path %>